language: node_js
sudo: required
node_js:
  - 8.12.0
cache:
  directories:
    - node_modules
before_install:
  - echo "before_install"
install:
  - yarn install
before_script:
  - echo "before_script"
script:
  - yarn docs:build
branch: dev
after_script:
  - cd ./docs/.vuepress/dist
  - git init
  - git add -A
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${TAR_BRANCH}