language: node_js
sudo: required
node_js:
  - 8.12.0
cache:
  directories:
    - node_modules
before_install:
  - echo "before_install"
install:
  - yarn install
before_script:
  - echo "before_script"
script:
  - yarn docs:build
branch: dev
deploy:
  provider: pages
  skip-cleanup: true
  repo: $GH_REF
  name: $GH_NAME
  email: $GH_EMAIL
  github-token: $GH_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: $TAR_BRANCH
  local-dir: ./docs/.vuepress/dist