language: node_js
sudo: required
node_js:
  - 8.12.0
cache:
  directories:
    - node_modules
branch: dev
before_install:
  - echo "before_install"
install:
  - yarn install
before_script:
  - echo "before_script"
script:
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: $GH_REF
  keep-history: true
  target-branch: master
  name: $GH_NAME
  email: $GH_EMAIL
  on:
    branch: $REP_BRANCH