language: node_js
sudo: required
node_js:
  - 8.12.0
cache:
  directories:
    - node_modules
branch: dev
before_install:
  - echo "before_install"
install:
  - yarn install
before_script:
  - echo "before_script"
script:
  - yarn run docs:build
after_success:
  - cd ./docs/.vuepress/dist
  - git init
  - git config user.name "${U_NAME}"
  - git add -A
  - git commit -m "Auto Update by Travis-CI"
  - echo git push --force "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master