language: node_js
sudo: required
node_js:
  - 8.12.0
cache:
  directories:
    - node_modules
before_install:
  - echo "before_install"
install:
  - yarn install
before_script:
  - echo "before_script"
script:
  - ./deploy.sh
